/**
 * Shapes of the datasets bundled with the app (`assets/data/*.skydata`, JSON).
 *
 * They are what lets a flight be prepared with no server at all: airports to
 * pick from, places to show along the route, and country outlines to stamp the
 * passport with. All are generated by `scripts/data/*.mjs` from public-domain or
 * permissively licensed sources; none is edited by hand.
 *
 * Keys are short on purpose — the files ship inside the app binary.
 */

/** Languages the datasets carry names for, besides English. */
export type DataLang = 'ru' | 'de' | 'fr' | 'es' | 'ja';

export type LocalNames = Partial<Record<DataLang, string>>;

/** [minLon, minLat, maxLon, maxLat] */
export type BBox = [number, number, number, number];

/** A ring of [lon, lat] pairs, first point not repeated. */
export type Ring = [number, number][];

/** Polygon = outer ring followed by holes. MultiPolygon = list of polygons. */
export type Polygon = Ring[];
export type MultiPolygon = Polygon[];

export type PlaceKind =
  | 'city'
  | 'mountain'
  | 'volcano'
  | 'range'
  | 'desert'
  | 'plateau'
  | 'lake'
  | 'river'
  | 'sea'
  | 'island'
  | 'peninsula'
  | 'glacier'
  | 'region'
  | 'landmark';

export interface DataPlace {
  /** Stable id, prefixed by source layer, e.g. "ne-pp-1234". */
  id: string;
  k: PlaceKind;
  /** English name. */
  n: string;
  l?: LocalNames;
  /** Label point. For areas, a point inside the area. */
  lat: number;
  lon: number;
  /** Importance 1–10, 10 = world-famous. Drives selection when places compete. */
  r: number;
  /** Population, cities only. */
  pop?: number;
  /** Elevation in metres, peaks and volcanoes. */
  el?: number;
  /** ISO 3166-1 alpha-2 of the country it lies in, when known. */
  cc?: string;
  /** Wikidata id, e.g. "Q649" — the key the app resolves Wikipedia articles by. */
  wd?: string;
  /** Areas only: rough half-size in km, used for visibility and ranking. */
  ext?: number;
  /** Areas only: bounding box. The outline itself lives in areas.json under the same id. */
  bb?: BBox;
}

export interface PlacesFile {
  version: 1;
  source: string;
  places: DataPlace[];
}

/** Outlines of area places (ranges, deserts, seas, lakes …), keyed by place id. */
export interface AreasFile {
  version: 1;
  areas: Record<string, MultiPolygon>;
}

export interface DataCountry {
  /** ISO 3166-1 alpha-2. Disputed or unrecognised areas use a stable pseudo-code, e.g. "XK". */
  cc: string;
  n: string;
  l?: LocalNames;
  /** Continent, English, e.g. "Europe". */
  cont: string;
  bb: BBox;
  g: MultiPolygon;
}

export interface CountriesFile {
  version: 1;
  source: string;
  countries: DataCountry[];
}

export interface DataAirport {
  /** IATA code. */
  i: string;
  /** ICAO code, when known. */
  c?: string;
  /** Airport name, English. */
  n: string;
  /** City served, English. */
  city: string;
  /** City name in other languages, when a confident match exists. */
  cl?: LocalNames;
  /** ISO 3166-1 alpha-2. */
  cc: string;
  lat: number;
  lon: number;
  /** IANA time zone, e.g. "Europe/Moscow". */
  tz: string;
  /** Size: 3 = large hub, 2 = medium, 1 = small with scheduled service. */
  s: 1 | 2 | 3;
}

export interface AirportsFile {
  version: 1;
  source: string;
  airports: DataAirport[];
}
